package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	gqlutils "github.com/lwinmgmg/user-go/graph/gql-utils"
	"github.com/lwinmgmg/user-go/graph/model"
	"github.com/lwinmgmg/user-go/internal/models"
)

// Partner is the resolver for the partner field.
func (r *userResolver) Partner(ctx context.Context, obj *model.User) (*model.Partner, error) {
	partner, err := models.GetPartnerByID(uint(obj.PartnerID), r.RoDb)
	if err != nil {
		return nil, err
	}
	return gqlutils.ContructPartner(partner), nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
