// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Partner struct {
	ID               int     `json:"id"`
	FirstName        string  `json:"firstName"`
	LastName         *string `json:"lastName,omitempty"`
	Email            string  `json:"email"`
	Phone            string  `json:"phone"`
	IsEmailConfirmed bool    `json:"isEmailConfirmed"`
	IsPhoneConfirmed bool    `json:"isPhoneConfirmed"`
	Code             string  `json:"code"`
}

type Query struct {
}

type User struct {
	ID              int      `json:"id"`
	Code            string   `json:"code"`
	Username        string   `json:"username"`
	Password        string   `json:"password"`
	PartnerID       int      `json:"partnerId"`
	Partner         *Partner `json:"partner"`
	OtpURL          *string  `json:"otpUrl,omitempty"`
	IsAuthenticator bool     `json:"isAuthenticator"`
}
